---
- name: Install Zabbix
  hosts: zabbix
  become: yes
  tasks:
    - name: Install package
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

    - name: Update cache
      apt:
        update_cache: yes

    - name: Install Zabbix components
      apt:
        pkg:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - php8.1-pgsql
        - zabbix-apache-conf
        - zabbix-sql-scripts
        - zabbix-agent

    - name: Add Zabbix user to Postgres
      expect: 
        command: "sudo -u postgres createuser --pwprompt zabbix"
        responses:
          "Enter password for new role:": "{{ zabbix_db_password }}\n"
          "Enter it again:": "{{ zabbix_db_password }}\n"
      tags:
        - user_create
      ignore_errors: yes

    - name: Add Zabbix DB
      command: "sudo -u postgres createdb -O zabbix zabbix"
      tags:
        - db_create
      ignore_errors: yes

    - name: unpack sql script
      command: gunzip /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
      tags: unpack
      ignore_errors: yes

    - name: Add Zabbix schema
      expect:      
        command: sudo -u zabbix psql -d zabbix -f /usr/share/zabbix-sql-scripts/postgresql/server.sql
        responses:
          "Password for user zabbix:": "{{ zabbix_db_password }}\n"
        timeout: 600
      tags:
        - schema
      ignore_errors: yes

    - name: Add password to zabbix.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regex: '^# DBPassword=password'
        line: DBPassword={{ zabbix_db_password }}
      ignore_errors: yes

    - name: Add Zabbix to root location
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regex: '^	DocumentRoot /var/www/html'
        line:        DocumentRoot /usr/share/zabbix

    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
  vars_files:
    - vault-file.yaml
